/**:
  ros__parameters:
    robot_description_kinematics:
      fanuc_m16ib:
        kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
        kinematics_solver_search_resolution: 0.005
        kinematics_solver_timeout: 0.005
        kinematics_solver_attempts: 3

        # kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
        # position_only_ik: true
        # solve_type: Distance # Speed, Manipulation1, Manipulation2, Distance
        # kinematics_solver_timeout: 0.5 # 0.005
        # kinematics_solver_attempts: 10
        # epsilon: 1e-5


  
#use this configs for standard kdl ik solver:
        # kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
        # kinematics_solver_search_resolution: 0.005
        # kinematics_solver_timeout: 0.005
        # kinematics_solver_attempts: 3

  # epsilon
  # kinematics_solver_attempts
  # kinematics_solver_ik_links
  # kinematics_solver_search_resolution
  # kinematics_solver_timeout
  # position_only_ik
  # solve_type
