__version__:
  serializer: 1
  data: 21
Settings:
  Acquisitions:
    - Acquisition:
        Aperture: 12.34
        Brightness: 1.8
        ExposureTime: 10000
        Gain: 1
    - Acquisition:
        Aperture: 3.36
        Brightness: 1.8
        ExposureTime: 10000
        Gain: 1
  Diagnostics:
    Enabled: no
  Experimental:
    Engine: phase
  Processing:
    Color:
      Balance:
        Blue: 1
        Green: 1
        Red: 1
      Experimental:
        Mode: automatic
      Gamma: 0.8
    Filters:
      Cluster:
        Removal:
          Enabled: yes
          MaxNeighborDistance: 6
          MinArea: 40
      Experimental:
        ContrastDistortion:
          Correction:
            Enabled: yes
            Strength: 0.2
          Removal:
            Enabled: yes
            Threshold: 0.3
        HoleFilling:
          Enabled: yes
          HoleSize: 0.07
          Strictness: 3
      Noise:
        Removal:
          Enabled: yes
          Threshold: 1
        Repair:
          Enabled: yes
        Suppression:
          Enabled: yes
      Outlier:
        Removal:
          Enabled: yes
          Threshold: 20
      Reflection:
        Removal:
          Enabled: yes
          Experimental:
            Mode: global
      Smoothing:
        Gaussian:
          Enabled: no
          Sigma: 2
  RegionOfInterest:
    Box:
      Enabled: no
      Extents: [-10, 100]
      PointA: [0, 0, 0]
      PointB: [0, 0, 0]
      PointO: [-222.366806, 184.023407, 490.959564]
    Depth:
      Enabled: yes
      Range: [300, 900]
  Sampling:
    Color: rgb
    Pixel: all
