#this file specifies a collision-free initial position for our robot_model

#NOTE: can be adapted when integrating this package into a whole scene

joint1: 0
joint2: 0
joint3: 0
joint4: 0
joint5: 0
joint6: 0
